name : test workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm ci #more fast than npm install
      - run : npx tsc --noEmit || true #check type (non-blocking for now)
      - run: npm test -- --watchAll=false
      - run: npm audit --audit-level=moderate #check security vulnerabilities